apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    dyskComponent: kernel-kubernetes-installer
  name: dysk-kubernetes-installer
  namespace: dysk-system
spec:
  template:
    metadata:
      labels:
        dyskComponent: dysk-kubernetes-installer
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: "true"
        effect: NoSchedule
      containers:
      - name: kernel-module-installer
        imagePullPolicy: Always
        image: "khenidak/dysk-installer:0.4"
        env:
        #forces the container not to exit 
        # to solve for this https://github.com/kubernetes/kubernetes/issues/17182
        # until it is fixed
        - name: INSTALL_MODE
          value: "kubernetes"
        #use this to control which version of dysk module 
        # do you want to install
        - name: DYSK_TAG
          value: 53184b8aa105a0f8a5c828c2178c900be6a66ee0
        resources:
          requests:
            cpu: 100m
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/usr/src"
          name: src
        - mountPath: "/lib/modules"
          name: modules
          readOnly: true
      # Todo: flex vol installer container
      volumes:
      - hostPath:
          path: "/usr/src"
        name: src
      - hostPath:
          path: "/lib/modules"
        name: modules
      nodeSelector:
        beta.kubernetes.io/os: linux
